import { useEffect, useRef, useState } from "react";
import MessageBubble from "./MessageBubble.jsx";
import TypingIndicator from "./TypingIndicator.jsx";

const SUGGESTIONS = [
  "Where is my order #1005?",
  "What is your refund policy?",
  "Can I cancel an order after it ships?",
  "I'd like to speak to a human",
];

export default function ChatWindow({ messages, isLoading, onSend, hasConversation }) {
  const [draft, setDraft] = useState("");
  const scrollRef = useRef(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, isLoading]);

  const submit = (text) => {
    const trimmed = (text ?? draft).trim();
    if (!trimmed || isLoading) return;
    onSend(trimmed);
    setDraft("");
  };

  const handleKeyDown = (e) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      submit();
    }
  };

  return (
    <div className="flex h-full flex-1 flex-col bg-paper-100">
      <div ref={scrollRef} className="flex-1 overflow-y-auto px-6 py-8">
        <div className="mx-auto flex max-w-2xl flex-col gap-4">
          {!hasConversation || messages.length === 0 ? (
            <div className="flex flex-col items-center justify-center gap-4 pt-24 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-signal-light">
                <svg width="22" height="22" viewBox="0 0 16 16" fill="none">
                  <path
                    d="M2 4a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H8l-3.5 3v-3H4a2 2 0 0 1-2-2V4Z"
                    stroke="#4C5FD5"
                    strokeWidth="1.3"
                    strokeLinejoin="round"
                  />
                </svg>
              </div>
              <div>
                <h2 className="font-display text-lg font-semibold text-ink-900">
                  How can we help today?
                </h2>
                <p className="mt-1 text-sm text-ink-600">
                  Ask about an order, a policy, or anything else.
                </p>
              </div>
              <div className="flex flex-wrap justify-center gap-2 pt-2">
                {SUGGESTIONS.map((s) => (
                  <button
                    key={s}
                    onClick={() => submit(s)}
                    className="rounded-full border border-paper-200 bg-white px-3.5 py-1.5 text-sm text-ink-700 transition hover:border-signal hover:text-signal-dark"
                  >
                    {s}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            messages.map((m) => <MessageBubble key={m.id} message={m} />)
          )}

          {isLoading && (
            <div className="flex justify-start">
              <TypingIndicator />
            </div>
          )}
        </div>
      </div>

      <div className="border-t border-paper-200 bg-paper-100 px-6 py-4">
        <div className="mx-auto flex max-w-2xl items-end gap-2 rounded-2xl border border-paper-200 bg-white p-2 shadow-panel">
          <textarea
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Message support..."
            rows={1}
            className="max-h-32 flex-1 resize-none bg-transparent px-3 py-2 text-sm text-ink-900 outline-none placeholder:text-ink-600"
          />
          <button
            onClick={() => submit()}
            disabled={!draft.trim() || isLoading}
            className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-signal text-white transition hover:bg-signal-dark disabled:cursor-not-allowed disabled:opacity-40"
            aria-label="Send message"
          >
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
              <path
                d="M2 8h11.5M8.5 3 13.5 8l-5 5"
                stroke="currentColor"
                strokeWidth="1.6"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </button>
        </div>
        <p className="mx-auto mt-2 max-w-2xl text-center text-xs text-ink-600">
          Answers are generated by AI and grounded in TechNova's policies.
        </p>
      </div>
    </div>
  );
}
